# Generated by Django 6.0.3 on 2026-04-15 11:25

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Complete', 'Complete'), ('Upcoming', 'Upcoming'), ('Ongoing', 'Ongoing'), ('Cancelled', 'Cancelled')])),
                ('type', models.CharField(choices=[('Seminar', 'Seminar'), ('Workshop', 'Workshop'), ('Placement', 'Placement Drive'), ('Cultural', 'Cultural'), ('Sports', 'Sports'), ('Other', 'Other')])),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('date', models.DateTimeField()),
                ('venue', models.CharField(max_length=200)),
                ('capacity', models.IntegerField()),
                ('department', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('reminder_sent', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'events',
                'ordering': ['date'],
            },
        ),
    ]
