# Generated by Django 6.0.3 on 2026-04-11 10:46

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Complete', 'Complete'), ('Upcoming', 'Upcoming'), ('Ongoing', 'Ongoing'), ('Cancelled', 'Cancelled')])),
                ('type', models.CharField(choices=[('Seminar', 'Seminar'), ('Workshop', 'Workshop'), ('Placement', 'Placement Drive'), ('Cultural', 'Cultural'), ('Sports', 'Sports'), ('Other', 'Other')])),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('date', models.DateTimeField()),
                ('venue', models.CharField(max_length=200)),
                ('capacity', models.IntegerField()),
                ('department', models.CharField(blank=True, help_text='Leave blank for all departments', max_length=100)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('reminder_sent', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'events',
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='NotificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sent_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('recipients_count', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('Sent', 'Sent'), ('Failed', 'Failed')], default='Sent', max_length=20)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_logs', to='event.events')),
            ],
            options={
                'db_table': 'notification_log',
            },
        ),
    ]
