# Generated by Django 6.0.3 on 2026-04-16 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notifications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(max_length=400)),
                ('event_id', models.CharField(max_length=400)),
            ],
            options={
                'db_table': 'notifications',
            },
        ),
    ]
