# Generated by Django 6.0.3 on 2026-04-11 16:24

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_alter_events_created_at_alter_events_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
