# Generated by Django 6.0.3 on 2026-04-16 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0003_notifications'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notifications',
            old_name='event',
            new_name='notification_id',
        ),
    ]
