# Generated by Django 6.0.3 on 2026-04-12 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0003_alter_events_created_at'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NotificationLog',
        ),
    ]
