# Generated by Django 6.0.3 on 2026-04-17 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0004_rename_event_notifications_notification_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notifications',
        ),
    ]
