# Generated by Django 6.0.3 on 2026-04-15 11:25

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('subject', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('Notes', 'Notes'), ('Assignment', 'Assignment'), ('Syllabus', 'Syllabus'), ('Previous_paper', 'Previous Year Paper'), ('Reference', 'Reference Material'), ('Other', 'Other')], default='notes', max_length=20)),
                ('department', models.CharField(choices=[('MCA', 'MCA'), ('BCA', 'BCA'), ('BSc CS', 'BSc CS'), ('MSc DS', 'MSc Data Science')], max_length=100)),
                ('uploaded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('download_count', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'resource',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
