# Generated by Django 6.0.3 on 2026-04-11 10:46

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('subject', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('Notes', 'Notes'), ('Assignment', 'Assignment'), ('Syllabus', 'Syllabus'), ('Previous_paper', 'Previous Year Paper'), ('Reference', 'Reference Material'), ('Other', 'Other')], default='notes', max_length=20)),
                ('department', models.CharField(max_length=100)),
                ('uploaded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('download_count', models.IntegerField(default=0)),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_resources', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'resource',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
