# Generated by Django 6.0.3 on 2026-04-12 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='department',
            field=models.CharField(choices=[('MCA', 'MCA'), ('BCA', 'BCA'), ('BSc CS', 'BSc CS'), ('MSc DS', 'MSc Data Science')], max_length=100),
        ),
    ]
